### ISSUE TITLE
Peg orderbook prices to a specific public key

### ISSUE THREAD

**Issue by particle4dev** [KomodoPlatform/dicoapp-e#3]
**Currently:**
Orderbook right now autoselects the lowest price printed in the orderbook, indifferent from which server or what price is being printed. Right now, if someone sets an order with a price much lower than current prices on a server with empty wallets, it can render the dicoapp unusable. 

**Expected:**
In the original dicoapp there was a parameter that could set a specific pubkey of a server to pull prices from. That way, price front running is blocked. 

**STEPS TO REPRODUCE:**
In the original app there was a file like this:

> `~/dicoapp/imports/api/config$ cat tokenconfig.js 
> let tokenconfig = {
>     dICOtoken: {
>         name: 'GLX Token',
>         shortcode: 'GLXT',
>         siteurl: 'https://glx.co',
>         supporturl: 'https://glx.co',
>         pricebob: 'b30ab074d57e2aa0f639ae9bc5965792ceb6270c64561a612e421c43b2a4fd13',
>         netid: 0,
>         seed: '0.0.0.0'
>     }
> };`

Pricebob parameter would read prices only from one pubkey. If the parameter was set to 0 it would be null and just read the first price printed in the orderbook.

**Related issues**
https://github.com/particle4dev/dicoapp-e/issues/73

**Comment by ca333** [comment]
yes - in the original app we did chose the bob hardcoded via pubkey to prevent this issue. Siu requested the removal of hardcoded pubkey check. I ll add the condition again and point you to it.

**Comment by ca333** [comment]
https://github.com/KomodoPlatform/dicoapp-e/commit/ae096f6fddb5a1967852f7426f40c758e6b87d5c
