### ISSUE TITLE
App shouldn't load a white, empty screen

### ISSUE THREAD

**Issue by bartwr** [KomodoPlatform/dicoapp-e#56]
Title: App shouldn't load a white, empty screen

**Currently:**

I execute `yarn dev`. A Chrome window opens. The inspector for this Chrome window opens as well. 

_But the app does not load._ It loads a white screen.

**Expected:**

I expect the app to load correctly.

**STEPS TO REPRODUCE:**

Have:

- npm version: 6.1.0
- node version: 10.3.0
- yarn version: 1.10.1

Execute:

    git clone git@github.com:KomodoPlatform/dicoapp-e.git
    cd dicoapp-e
    git checkout develop
    yarn install
    yarn dev

**REFERENCE:**

Console logs:

![image](https://user-images.githubusercontent.com/899234/46917983-b6aeff00-cfcc-11e8-851b-94f0dcc12ae4.png)

```Uncaught TypeError: Cannot read property 'get' of undefined
    at logoutState (selectors.js:7)
    at eval (index.js:75)
    at eval (index.js:35)
    at eval (index.js:89)
    at eval (index.js:35)
    at eval (index.js:85)
    at Function.eval [as mapToProps] (index.js:35)
    at mapToPropsProxy (wrapMapToProps.js:48)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:57)
    at mapToPropsProxy (wrapMapToProps.js:48)
```

![code snippet](https://i.imgur.com/fdbmh87.png)

**Possible fixes:**

It gives an error regarding the `makeSelectLogoutState` function in `/app/containers/LogoutDialog/selectors.js`.

This is not a real fix, but a workaround I did:

If I change the function to `makeSelectLogoutState = () => function(){}` and back to `const makeSelectLogoutState = () => createSelector(selectLogoutState, logoutState => logoutState.get('show'));` the seed login screen shows up.

**Summary:**

**White screen on `yarn dev` - what to do?**

/label ~bug

**Comment by particle4dev** [comment]
@bartwr thanks for reporting the issue. I'm trying to reproduce it.
During this time, please try to replace mm app with worked one.
This one is worked:
https://github.com/KomodoPlatform/dicoapp/tree/master/.desktop/modules/marketmaker
Try to replace here:
https://github.com/KomodoPlatform/dicoapp-e/tree/develop/app/bin/marketmaker

**Comment by particle4dev** [comment]
update -- I didn't get this issue, the app run normally in my local. It seems replacing mm app sovle this issue. Closed. Feel free to reopen if you still get this.

For more information, my environment setup:

- OS: OSX
- npm version: 6.3.0
- node version: v9.11.2
- yarn version: 1.9.4

<img width="1054" alt="screen shot 2018-10-14 at 23 32 30" src="https://user-images.githubusercontent.com/3245868/46919434-85a0ef80-d009-11e8-875f-da687c7e7b37.png">

**Comment by bartwr** [comment]
@particle4dev Thank you for your reply. I've solved it; below I sharel find my findings.

____

I replaced the marketmaker with the [marketmaker](https://github.com/KomodoPlatform/dicoapp/tree/master/.desktop/modules/marketmaker) suggested by you.

The error remained, both in `master` and `develop`.

____

I used `yarn dev`, and tried `yarn start`. It works way better now, though I get the following error:

![image](https://user-images.githubusercontent.com/899234/46919646-a7d34700-cfe2-11e8-8d50-0f7aeaea32b1.png)

I see that the script does not refer well to the marketmaker binary. It links to `../bin/marketmaker/linux/marketmaker` instead of `bin/marketmaker/linux/marketmaker`.

____

I opened `app/main/plugins/marketmaker.js` in my IDE. On line 43 I hardcoded the `marketmaker` file path.

![image](https://user-images.githubusercontent.com/899234/46919667-e9fc8880-cfe2-11e8-9164-d5c75b17ab32.png)

Now, if I do a `yarn start` everything works well!

____

Conclusion: Problem diagnosed & solved by hard coding my marketmaker path. Main takeaway: Use `yarn start` and not `yarn dev`.

**Comment by particle4dev** [comment]
yarn start - it starts the application in production mode. You can use it but the code doesn't live-reload when you change it.
It seems you run it in Ubuntu. Maybe @siulynot can help me to reproduce this issue.
Did you get this issue with a fresh start, @siulynot?
P/S: Hope you can be logged in the app now @bartwr  :)

**Comment by bartwr** [comment]
>  Did you get this issue with a fresh start?

Yes, I got the issue with a fresh start. Fresh clone from GitHub. Although I'm using my main machine = not a freshly installed Ubuntu OS.

>  It seems you run it in Ubuntu. Maybe siulynot can help me to reproduce this issue.

Would be great :]

>  P/S: Hope you can be logged in the app now :)

Yes - I'm logged in!

**Comment by bartwr** [comment]
*For future reference:*

Problem: If I run `yarn start`, I first get a EACCESS error. Then, if I try to login, I get "Network error".

Related problem: If I execute the `/linux/marketmaker` file manually per Terminal, I get `[1]    29478 segmentation fault (core dumped)`

Solution:

1. In `marketmaker.js`, replace `config.get('paths.marketmaker')` with the hard coded marketmaker path
2. Download a recent version of `marketmaker` and replace the one that is currently in this repository
