### ISSUE TITLE
implement transactions tab

### ISSUE THREAD

**Issue by particle4dev** [KomodoPlatform/dicoapp-e#64]
Title: implement transactions tab

Business/User Value:

User objectives:

- filter trasactions by coin

Acceptance Criteria
GIVEN [necessary context and preconditions for story]
WHEN [action]
THEN [reaction]

**DEV NOTES**

- https://github.com/KomodoPlatform/KomodoPlatform/wiki/BarterDEX-API-Summary-by-Category

**DESIGN Notes**
None

---other items that you may add to a story---

**NEEDS PM**
None

**NEEDS DESIGN**
None

**Related issues**
#15 

/label ~"story"

**Comment by particle4dev** [comment]
This is user objectives that user want to satisfy when they open the transaction tab in wallet page:

- The user wants to know when the transaction happen

- The user wants to know the amount of transaction

- The user wants to know what type of transaction (withdraw, deposit)

Currently, `listtransactions` api only returns tx_hash and height in SPV mode.
```
{
    "tx_hash": "afc2fd0991bdef89da2cd1018c86ab56a5989c6f2b1d4e40861e88bc6125cbec",
    "height": 10076
}
```
Is there any other way for me to get the above information (time, amount, type)?
cc @ca333 @siulynot @artemii235 @pbca26

**Comment by artemii235** [comment]
@particle4dev Hi, does it return more info in native mode?

**Comment by particle4dev** [comment]
@artemii235 yes, but the purpose of the app is used SPV lightweight mod. Is there an API that I can call with `tx_hash` to receive more detail?

**Comment by artemii235** [comment]
@particle4dev I'll check what can be done tomorrow and let you know. If it's possible to fix it fast I'll publish the new release right away.

**Comment by particle4dev** [comment]
@artemii235 awesome, thank you :D

**Comment by particle4dev** [comment]
Don't worry if you can not.
We can hold this task until we find out the best solution. No rush

**Comment by artemii235** [comment]
@particle4dev Hi, I've checked the code responsible for tx history and seems like there is no "easy" way to reduce the execution time of `listtransactions`. The response is got directly from electrum server and it contains only tx hash and height without other tx data. Also electrum `get_history` takes really long (especially for first time). So here are steps that I need to implement:
1. Call electrum `get_history` at background thread.
2. Collect transactions by hashes.
3. Transform the collected data and save it at memory/storage.
4. Respond to `listtransactions` with previously prepared data.
It'll allow to provide `listtransactions` response immediately but as you can see it requires some work to prepare the data.

I think it'll take 1-2 days to implement it, I'll have time for it on next week.
A question about response format: do you have specific requirements for it? Or it can be same as `listtransactions` in native mode?

**Comment by particle4dev** [comment]
@artemii235 What a good new!
We should support backward compatible so it doesn't break the app if someone is using that API.
```
Or it can be same as listtransactions in native mode?
```
Yes, it's good if it can look the same with native mode.
Easy to remember.
Thanks : )

**Comment by artemii235** [comment]
@particle4dev Hi Nam, excuse me, wasn't able to finish the task on prev week, going to finish on this one.

**Comment by particle4dev** [comment]
@artemii235 hi, that's ok :) thank you so much for hard work

**Comment by artemii235** [comment]
@particle4dev Hi Nam, I've finished implementation and published the new release: https://github.com/artemii235/SuperNET/releases/tag/v1.0.928
Please check following example of listtransaction response in Electrum mode:
```
[
  {
    "txid":"5b4f40383d24504c674325585fa5ab6d478c3ebbf60ec83643ddb27ac536e4af",
    "category":"receive",
    "amount":1.12500999,
    "blockhash":"04c29068c00379e6c59e737e4e7f590407b445b7995d25d4f49b824b64ac391b",
    "blockindex":130530,
    "blocktime":1541574432,
    "time":1541574432,
    "confirmations":5
  },
  {
    "txid":"4d83285b73070d9b7bc4f9ba140bb4bd9248375686bab82d4b7d5adff1c9123a",
    "category":"send",
    "amount":-1.00001999,
    "blockhash":"0a9d036274f0953aa6e62fd8935a79f1a96709ade8bffc509192b3511f209ac4",
    "blockindex":130528,
    "blocktime":1541574338,
    "time":1541574338,
    "confirmations":7
  }
]
```
As I said before the history is getting loaded in background so it might take some time to load full history, it starts loading from recent transactions so the more transactions address has the more time it'll take to load them all - it does not block `listtransactions` request, you should just keep in mind that you might not get old transactions immediately especially if there are hundreds of them.
Also in comparison with native some fields are omitted (txfee, etc.) because Electrum doesn't provide them.
Please test the release and let me know if I need to fix or add something.

**Comment by particle4dev** [comment]
@artemii235 thanks. I will test it today and send you the feedback. Now I'm working on other task

**Comment by particle4dev** [comment]
@artemii235 the API work great. I like it a lot. Closed this issue for now.
I need to work on searching transaction feature but still don't know what should UI/UX looks like. I have to research more about it to find what user want.
